<?php

namespace app\common\model;
use app\common\util\TpshopException;
use think\Model;
class GoodsAttribute extends Model {

    public function GoodsAttr()
    {
        return $this->hasOne('GoodsAttr','attr_id','attr_id');
    }
    public function getAttrValuesToArrayAttr($value, $data)
    {
        if($data['attr_values'] != ''){
            return explode(',', $data['attr_values']);
        }
        return [];
    }

    public function delete()
    {
        $attr_id = $this->getAttr('attr_id');
        $goods_attr = db('goods_attr')->where('attr_id', $attr_id)->find();
        if($goods_attr){
            $goods_name = db('goods')->where('goods_id', $goods_attr['goods_id'])->value('goods_name');
            throw new TpshopException('删除规格值', 0, ['status' => 0, 'msg' => $goods_name . '在使用该属性项，不能删除']);
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
